import { admit, Ledger, type Reservation } from "@ao/core";
import { DEFAULT_GOAL_CONFIG } from "@ao/core/plan";
import {
  BudgetExceededError,
  toSerializedError,
  type GoalConfig,
  type LLMProvider,
  type Message,
  type Usage,
} from "@ao/shared";
import { resolveModelEntry } from "@ao/providers";
import type { SqlDriver } from "../db/driver.js";
import { genRunId } from "../db/ids.js";
import { insertMessage, listMessages, type ChatMessage } from "../db/messages.repo.js";
import { createRun, finishRun } from "../db/runs.repo.js";
import { touchThread } from "../db/threads.repo.js";
import type { EventHub } from "../ws/hub.js";

const CHAT_STAGE_ID = "chat";

/** Only used when a model id isn't in the pricing registry at all (shouldn't happen for `ctx.model`, which is validated at startup) — gemini-3.7-flash's real cap, so the worst-case estimate stays conservative rather than silently shrinking. */
const FALLBACK_MAX_OUTPUT_TOKENS = 64_000;

function toProviderRole(role: ChatMessage["role"]): "user" | "model" {
  return role === "assistant" ? "model" : "user";
}

/** Turns a raw `admit`/settlement failure into the same `{scope,code,message,recoverable}` wire shape the WS `error` event and the streaming-failure catch block below both use. */
function publishError(hub: EventHub, runId: string, error: unknown): void {
  const serialized = toSerializedError(error);
  hub.publish(runId, "error", {
    scope: serialized.scope,
    code: serialized.code,
    message: serialized.message,
    recoverable: serialized.recoverable,
  });
}

export interface RunChatTurnOptions {
  driver: SqlDriver;
  hub: EventHub;
  provider: LLMProvider;
  model: string;
  threadId: string;
  /**
   * Pre-generated by the caller (routes/messages.ts) so the HTTP response
   * can hand the client a `runId` to subscribe to over WS before this
   * function's async work (the provider call) resolves — this function is
   * normally invoked without being awaited by the route handler. Defaults
   * to a fresh id for direct/test callers that don't need that.
   */
  runId?: string;
  /**
   * The goal button's settings for this thread (P9-T1), normally the
   * caller's already-loaded `thread.goalConfig` (never `undefined` there —
   * threads.repo.ts falls back to DEFAULT_GOAL_CONFIG itself). Defaults to
   * DEFAULT_GOAL_CONFIG here too, purely for direct/test callers that don't
   * go through a thread at all.
   */
  goalConfig?: GoalConfig;
}

export interface RunChatTurnResult {
  runId: string;
  assistantMessage: ChatMessage;
}

/**
 * P2's walking-skeleton chat turn — still no planner/scheduler (that's a
 * larger, separate wiring effort noted as an open gap, not part of P9-T1),
 * but as of P9-T1 it spends against a *real* `Ledger` sized from the goal
 * button's chosen budget, instead of a fixed unenforced constant. The user
 * message is expected to already be persisted by the caller (so its id can
 * be returned synchronously from the HTTP handler) — this function reads
 * the thread's full history (which therefore includes it), starts a run,
 * streams the provider's reply over the event bus chunk by chunk, persists
 * the assistant reply + usage, and closes out the run.
 */
export async function runChatTurn(options: RunChatTurnOptions): Promise<RunChatTurnResult> {
  const { driver, hub, provider, model, threadId } = options;
  const goalConfig = options.goalConfig ?? DEFAULT_GOAL_CONFIG;

  const history = listMessages(driver, threadId);
  const contents: Message[] = history.map((m) => ({
    role: toProviderRole(m.role),
    parts: [{ text: m.content }],
  }));

  const run = createRun(driver, threadId, options.runId ?? genRunId());
  const taskId = `${run.id}#0`;
  const ledger = new Ledger({
    total: goalConfig.budgetTotal,
    runId: run.id,
    pricing: (modelId) => resolveModelEntry(modelId)?.pricing,
  });

  hub.publish(run.id, "run.started", {
    runId: run.id,
    budget: goalConfig.budgetTotal,
    mode: goalConfig.level,
  });

  const contextTokens = await provider.countTokens({ model, contents }).catch(() => 0);
  const maxOutputTokens = resolveModelEntry(model)?.maxOutputTokens ?? FALLBACK_MAX_OUTPUT_TOKENS;
  const worstCase = contextTokens + maxOutputTokens;

  const admitOutcome = admit(ledger, {
    bucket: "execution",
    stageId: CHAT_STAGE_ID,
    agentType: "chat",
    worstCase,
  });

  let reservation: Reservation;
  if (admitOutcome.decision === "approved") {
    reservation = admitOutcome.reservation;
  } else if (goalConfig.overrunPolicy === "degrade") {
    // BUDGET.md §5 level 8: always succeeds, clamped to whatever is left in
    // the locked reserve. The chat path has no fan-out/read-rung/tier to
    // step down through first (levels 1-7 all target a multi-stage Plan,
    // which doesn't exist on this path) — drawing from reserve is the only
    // degradation lever a single call has.
    reservation = ledger.drawFromReserve(worstCase, { stageId: CHAT_STAGE_ID, agentType: "chat" });
  } else {
    // "ask" and "hard-stop" both mean: don't spend without either the
    // user's explicit go-ahead or an explicit stop. There's no mid-turn
    // "ask" UI yet (that's P9-T9/T11's job), so both surface the same
    // clear, non-silent error for now rather than silently degrading on
    // the user's behalf.
    const error = new BudgetExceededError(
      `the "${goalConfig.level}" budget (${String(goalConfig.budgetTotal)} tokens) can't cover this ` +
        `message: ${admitOutcome.reason}`,
    );
    publishError(hub, run.id, error);
    finishRun(driver, run.id, "failed");
    hub.publish(run.id, "run.finished", {
      status: "failed",
      deliverables: [],
      ledger: ledger.snapshot(),
      gaps: [],
    });
    throw error;
  }

  hub.publish(run.id, "task.started", { taskId, agentType: "chat", shard: "default", contextTokens });

  let assistantText = "";
  let usage: Usage | undefined;
  let finishReason = "stop";

  try {
    for await (const delta of provider.generate({ model, contents, thinkingLevel: goalConfig.effort })) {
      if (delta.text.length > 0 && !delta.isThought) {
        assistantText += delta.text;
        hub.publish(run.id, "task.delta", { taskId, envelope: { t: "note", text: delta.text } });
      }
      if (delta.usage) usage = delta.usage;
      if (delta.finishReason) finishReason = delta.finishReason;
    }
  } catch (error) {
    ledger.release(reservation);
    publishError(hub, run.id, error);
    finishRun(driver, run.id, "failed");
    hub.publish(run.id, "run.finished", {
      status: "failed",
      deliverables: [],
      ledger: ledger.snapshot(),
      gaps: [],
    });
    throw error;
  }

  const finalUsage = usage ?? { promptTokens: 0, candidatesTokens: 0, thoughtsTokens: 0, cachedTokens: 0 };
  ledger.settle(reservation, finalUsage, model);
  hub.publish(run.id, "task.finished", { taskId, usage: finalUsage, finishReason, violations: 0 });

  const assistantMessage = insertMessage(driver, {
    threadId,
    role: "assistant",
    content: assistantText,
    usage: finalUsage,
  });
  touchThread(driver, threadId);

  const snapshot = ledger.snapshot();
  hub.publish(run.id, "ledger.updated", {
    spent: snapshot.tokens.spent,
    committed: snapshot.tokens.committed,
    remaining: snapshot.tokens.available,
    // No stages left to run after a single chat turn, so a true rate-based
    // completion projection (BUDGET.md §8) isn't meaningful here yet — that
    // needs multiple stages/tasks to extrapolate from, which is P9-T6's job
    // once a real scheduler run exists. This is "what we'll have spent once
    // in-flight reservations settle", the honest analogue for one call.
    projection: snapshot.tokens.spent + snapshot.tokens.committed,
    byStage: Object.fromEntries(
      Object.entries(snapshot.byStage).map(([stageId, state]) => [stageId, state.spent + state.committed]),
    ),
  });

  finishRun(driver, run.id, "completed");
  hub.publish(run.id, "run.finished", { status: "completed", deliverables: [], ledger: snapshot, gaps: [] });

  return { runId: run.id, assistantMessage };
}
