import type { LLMProvider, Message, Usage } from "@ao/shared";
import { toSerializedError } from "@ao/shared";
import type { SqlDriver } from "../db/driver.js";
import { genRunId } from "../db/ids.js";
import { insertMessage, listMessages, type ChatMessage } from "../db/messages.repo.js";
import { createRun, finishRun } from "../db/runs.repo.js";
import { touchThread } from "../db/threads.repo.js";
import type { EventHub } from "../ws/hub.js";

/**
 * P2 has no real budget engine (that's P4) — this is a fixed, display-only
 * figure that exists only so `run.started`/`ledger.updated` (whose zod
 * schemas require a positive budget and a nonnegative `remaining`) stay
 * schema-valid. It is not enforced anywhere.
 */
const NOMINAL_BUDGET_TOKENS = 1_000_000;

function toProviderRole(role: ChatMessage["role"]): "user" | "model" {
  return role === "assistant" ? "model" : "user";
}

/** "Cost so far" = promptTokens + candidatesTokens + thoughtsTokens summed across a thread's assistant messages (P2-T8). cachedTokens is excluded — it's a discount on prompt cost, not additional spend. */
function sumUsage(messages: ChatMessage[]): number {
  let total = 0;
  for (const message of messages) {
    if (message.usage) {
      total += message.usage.promptTokens + message.usage.candidatesTokens + message.usage.thoughtsTokens;
    }
  }
  return total;
}

export interface RunChatTurnOptions {
  driver: SqlDriver;
  hub: EventHub;
  provider: LLMProvider;
  model: string;
  threadId: string;
  /**
   * Pre-generated by the caller (routes/messages.ts) so the HTTP response
   * can hand the client a `runId` to subscribe to over WS *before* this
   * function's async work (the provider call) resolves — this function is
   * normally invoked without being awaited by the route handler. Defaults
   * to a fresh id for direct/test callers that don't need that.
   */
  runId?: string;
}

export interface RunChatTurnResult {
  runId: string;
  assistantMessage: ChatMessage;
}

/**
 * P2's entire "orchestration": one chat turn, no planner/scheduler. The
 * user message is expected to already be persisted by the caller (so its
 * id can be returned synchronously from the HTTP handler) — this function
 * reads the thread's full history (which therefore includes it), starts a
 * run, streams the provider's reply over the event bus chunk by chunk,
 * persists the assistant reply + usage, and closes out the run.
 */
export async function runChatTurn(options: RunChatTurnOptions): Promise<RunChatTurnResult> {
  const { driver, hub, provider, model, threadId } = options;

  const history = listMessages(driver, threadId);
  const contents: Message[] = history.map((m) => ({
    role: toProviderRole(m.role),
    parts: [{ text: m.content }],
  }));

  const run = createRun(driver, threadId, options.runId ?? genRunId());
  const taskId = `${run.id}#0`;

  hub.publish(run.id, "run.started", { runId: run.id, budget: NOMINAL_BUDGET_TOKENS, mode: "standard" });

  const contextTokens = await provider.countTokens({ model, contents }).catch(() => 0);
  hub.publish(run.id, "task.started", { taskId, agentType: "chat", shard: "default", contextTokens });

  let assistantText = "";
  let usage: Usage | undefined;
  let finishReason = "stop";

  try {
    for await (const delta of provider.generate({ model, contents })) {
      if (delta.text.length > 0 && !delta.isThought) {
        assistantText += delta.text;
        hub.publish(run.id, "task.delta", { taskId, envelope: { t: "note", text: delta.text } });
      }
      if (delta.usage) usage = delta.usage;
      if (delta.finishReason) finishReason = delta.finishReason;
    }
  } catch (error) {
    const serialized = toSerializedError(error);
    hub.publish(run.id, "error", {
      scope: serialized.scope,
      code: serialized.code,
      message: serialized.message,
      recoverable: serialized.recoverable,
    });
    finishRun(driver, run.id, "failed");
    hub.publish(run.id, "run.finished", { status: "failed", deliverables: [], ledger: null, gaps: [] });
    throw error;
  }

  const finalUsage = usage ?? { promptTokens: 0, candidatesTokens: 0, thoughtsTokens: 0, cachedTokens: 0 };
  hub.publish(run.id, "task.finished", { taskId, usage: finalUsage, finishReason, violations: 0 });

  const assistantMessage = insertMessage(driver, {
    threadId,
    role: "assistant",
    content: assistantText,
    usage: finalUsage,
  });
  touchThread(driver, threadId);

  const spentTotal = sumUsage([...history, assistantMessage]);
  hub.publish(run.id, "ledger.updated", {
    spent: spentTotal,
    committed: 0,
    remaining: Math.max(0, NOMINAL_BUDGET_TOKENS - spentTotal),
    projection: spentTotal,
    byStage: { chat: spentTotal },
  });

  finishRun(driver, run.id, "completed");
  hub.publish(run.id, "run.finished", { status: "completed", deliverables: [], ledger: null, gaps: [] });

  return { runId: run.id, assistantMessage };
}
